name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Maven Build Stage
  maven-build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: my-app.jar  # Passing the artifact name to the next job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - name: Archive JAR File
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: my-app
          path: target/*.jar  # Upload the JAR file for the next job

  # Step 2: Docker Build Stage
  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build  # This job runs after Maven Build is complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Download Built JAR
        uses: actions/download-artifact@v4  # Updated version
        with:
          name: my-app
          path: target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest -f Dockerfile .

      - name: Save Docker Image
        run: docker save my-app:latest -o my-app.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: docker-image
          path: my-app.tar

  # Step 3: Docker Push Stage
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build  # This job runs after Docker Build is complete
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4  # Updated version
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i my-app.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker Image
        run: |
          docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
